name: habit_tracker_app
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5
  adaptive_action_sheet: ^2.0.2
  flutter_launcher_icons: ^0.9.3
  flutter_svg: ^1.1.1+1
  modal_bottom_sheet: ^2.1.0
  uuid: ^3.0.6
  flutter_bloc: ^8.0.1
  equatable: ^2.0.3
  isar: ^2.5.0
  isar_flutter_libs: ^2.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1
  build_runner: ^2.2.0
  isar_generator: ^2.5.0

flutter_icons:
  ios: true
  android: true
  remove_alpha_ios: true
  image_path_ios: "assets/app-icon.png"
  image_path_android: "assets/app-icon.png"
  adaptive_icon_background: "assets/app-icon-background.png"
  adaptive_icon_foreground: "assets/app-icon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/
